/*
 * Memory manager
 */

module Odin
{
   interface MemoryManager
   {
      void ctor();
      void dtor();

      uint create(
         uint type,
         uint param_count/* FIXME: need dynamic, uint param1, uint param2, uint param3*/
      );
      uint create_at(
         uint type,
         uint base,
         uint param_count/* FIXME: need dynamic, uint param1, uint param2, uint param3*/
      );
      uint destroy(
         comp to_go
      );

      uint install(
         uint img
      );
      void uninstall(
         uint type
      );

      uint get_addr(
         comp c
      );
      void linear(
         uint amnt
      );

      comp get_statistics(); // return statistics in well-defined-format read-only data comp
   };
};
