/*
 * Library OS bootstrapper
 *
 * Used to load and construct running image of library operating system.
 * Its run() method is used to start running library OS.
 */

module Odin
{
   interface Strapper : Runnable, Namespace
   {
   };
};
