<? // AUTOGENERATED FROM people_list by people_to_php.pl
   // DO NOT EDIT! make changes to people_list instead

$people = array(
	"glaw" => array(
		"name" => "Greg Law",
		"email" => "greglaw@users.sf.net"
	),
	"glom" => array(
		"name" => "German L. Osella Massa",
		"email" => "gosella@users.sf.net"
	),
	"berk" => array(
		"name" => "Stanislav Karchebny",
		"email" => "madfire@users.sf.net"
	),
	"aik" => array(
		"name" => "Igor Kucheryavenkov",
		"email" => "alar@users.sf.net"
	),
);

?>