/* simple console output (and even primitive input) */

interface Console
{
	void ctor();
	void dtor();

	void gotoxy( uint x, uint y );
	void print_int   ( int  i );
	void print_char  ( uint c );
	void print_dword ( uint d );
	void print_word  ( uint w );
	void print_byte  ( uint b );
	void print       ( string s );
	void scroll_up();
	void newline();

	void wait_ack();
	void debug_showregs();
	void debug_showstack();
	void debug_showmem();
};
