/*
 * This is local, ORB-specific interface allowing system components to
 * access ORB methods directly. It is never published to end-user components.
 * End-user components should use Library OS specific ORB interfaces, for example
 * Odin clients will use Odin::ORB interface.
 */

module ORB
{
   interface ORB
   {
      struct create_params
      {
         objref type;
         linear where;
         uint32 param_count;
         sequence<uint32> params;
      };

      void ctor();

      any call();
      any fcall();
      any tcall();
      void xfer();

      objref create(
         in reg<eax> uint32 count,
         in stack sequence<create_params> params
      );
      void destroy();

      ??? install();
      uninstall();

      lock();
      unlock();

      sel2ref();
      get_stack();
      set_desc();

      readonly attribute comp self; // get_self();
      attribute comp type; // get_type(); set_type();

      linear();
      fault();
      reject();
      switch_stacks();
      throw();
      ret();
      memory_map();
   };
};
